function serialSet = serialSetDialog(serials)


    win_h = 270;
    offsetX = -5;
    d = dialog('Position',[500 400 300 win_h],'Name','Serial Port Setting');

    warning('off','MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
    jFrame=get(handle(d), 'javaframe');
    jicon=javax.swing.ImageIcon('smart.png');
    jFrame.setFigureIcon(jicon);
    
    txt_port = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[offsetX win_h-60 110 40],...
           'String','Port:');
    
     popup_port = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42 80 25],...
           'String',serials,...
           'Callback',@popup_port_callback);
       
     txt_bitsSec = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-90 150 40],...
           'String','Bits/Sec (Baud Rate):');   
      
     
     popup_bitSec = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30 80 25],...
           'String',{'9600';'Green';'Blue'},...
           'Callback',@popup_bitSec_callback);  
       
     txt_databit = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-120 95 40],...
           'String','Data bits:');  
    
     
     popup_databit = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30 80 25],...
           'String',{'8';'Green';'Blue'},...
           'Callback',@popup_callback);  
  
     
     txt_parity = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-150 80 40],...
           'String','Parity:');  
       
       
     popup_parity = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30 80 25],...
           'String',{'None';'Green';'Blue'},...
           'Callback',@popup_callback);  
       
     txt_stopBit = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[21 + offsetX win_h-180 90 40],...
           'String','Stop bits:'); 
      
       
     popup_stopbit = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30-30 80 25],...
           'String',{'1';'Green';'Blue'},...
           'Callback',@popup_callback);  
       
     txt_flow = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[30 + offsetX win_h-210 90 40],...
           'String','Flow control:'); 
       
     popup_flow = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30-30-30 80 25],...
           'String',{'None';'Green';'Blue'},...
           'Callback',@popup_callback);  
      
    btn = uicontrol('Parent',d,...
           'Position',[offsetX+60 win_h-52-30*6 70 25],...
           'String','OK',...
           'Callback','delete(gcf)');
     
    
    btn_cancel = uicontrol('Parent',d,...
           'Position',[offsetX+160 win_h-52-30*6 70 25],...
           'String','Cancel',...
           'Callback','delete(gcf)');   
       
    idx = popup_port.Value;
    popup_port_items = popup_port.String;
    serialSet{1,1} = char(popup_port_items(idx,:));
    serialSet{1,2} = '9600';
    serialSet{1,3} = '8';
    serialSet{1,4} = 'None';
    serialSet{1,5} = '1';
    serialSet{1,6} = 'None';
    
    % Wait for d to close before running to completion
    uiwait(d);
  
   
       function popup_port_callback(popup,event)
          idx = popup_port.Value;
          popup_port_items = popup_port.String;
          serialSet{1,1} = char(popup_port_items(idx,:));
       end
   
        function popup_bitSec_callback(popup,event)
          idx = popup_bitSec.Value;
          popup_bitSec_items = popup_bitSec.String;
          serialSet{1,2} = char(popup_bitSec_items(idx,:));
       end
end