function serialSet = serialSetDialog


    win_h = 270;
    offsetX = -5;
    d = dialog('Position',[500 400 300 win_h],'Name','Serial Port Setting');

    warning('off','MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
    jFrame=get(handle(d), 'javaframe');
    jicon=javax.swing.ImageIcon('smart.png');
    jFrame.setFigureIcon(jicon);
    
    txt_port = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[offsetX win_h-60 110 40],...
           'String','Port:');
    
     popup_port = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42 80 25],...
           'String',{'COM1';'COM2';'COM3'},...
           'Callback',@popup_callback);
       
     txt_bitsSec = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-90 150 40],...
           'String','Bits/Sec (Baud Rate):');   
      
     
     popup_bitSec = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30 80 25],...
           'String',{'9600';'Green';'Blue'},...
           'Callback',@popup_callback);  
       
     txt_databit = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-120 95 40],...
           'String','Data bits:');  
    
     
     popup_databit = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30 80 25],...
           'String',{'8';'Green';'Blue'},...
           'Callback',@popup_callback);  
  
     
     txt_parity = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 + offsetX win_h-150 80 40],...
           'String','Parity:');  
       
       
     popup_parity = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30 80 25],...
           'String',{'None';'Green';'Blue'},...
           'Callback',@popup_callback);  
       
     txt_stopBit = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[21 + offsetX win_h-180 90 40],...
           'String','Stop bits:'); 
      
       
     popup_stopbit = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30-30 80 25],...
           'String',{'1';'Green';'Blue'},...
           'Callback',@popup_callback);  
       
     txt_flow = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[30 + offsetX win_h-210 90 40],...
           'String','Flow control:'); 
       
     popup_flow = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[offsetX+170 win_h-42-30-30-30-30-30 80 25],...
           'String',{'None';'Green';'Blue'},...
           'Callback',@popup_callback);  
      
    btn = uicontrol('Parent',d,...
           'Position',[offsetX+60 win_h-52-30*6 70 25],...
           'String','OK',...
           'Callback','delete(gcf)');
     
    
    btn_cancel = uicontrol('Parent',d,...
           'Position',[offsetX+160 win_h-52-30*6 70 25],...
           'String','Cancel',...
           'Callback','delete(gcf)');   
       
    serialSet = 'Red';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          % This code uses dot notation to get properties.
          % Dot notation runs in R2014b and later.
          % For R2014a and earlier:
          % idx = get(popup,'Value');
          % popup_items = get(popup,'String');
          serialSet = char(popup_items(idx,:));
       end
end